### ISSUE TITLE
404 Error?

### ISSUE THREAD

**Issue by ryanknutson** [mplewis/yot#3]
Whenever I try to get to any board it gives a 404 not found.

**Comment by mplewis** [comment]
Thanks for opening an issue. It's been a while since I worked on this app—let me see what is up.

**Comment by ryanknutson** [comment]
Okay thanks!

**Comment by mplewis** [comment]
Hey @ryanknutson,

I took a brief look at the problem, but I don't have time to diagnose what's wrong or continue maintaining this project unfortunately.

If you would like to build on what I have here, please feel free! You can always email me with questions at matt@mplewis.com.

**Comment by ryanknutson** [comment]
Okay thanks for looking at it! I'm not that good of a coder so I wouldn't be able to fix it. Btw, do you get the same error when you use it?

**Comment by tux1c** [comment]
https://github.com/mplewis/yot/pull/4
